server/views/editor.py
import os
from flask import Blueprint, flash, render_template, request, url_for, current_app, abort
from flask_security import current_user, auth_required
from werkzeug.utils import redirect
from models import User, File, Presentation, PresentationUser
from database import db_session
from file_manager import load_file_text, upload_file_from_txt
import datetime
import hashlib
import uuid

editor_pages = Blueprint("editor_pages", __name__, url_prefix='/editor')


@editor_pages.route("/<presentation>", methods=["GET", "POST"])
@auth_required()
def edit(presentation):
    #    presentation=presentation.split('?')[0]
    a = db_session.query(File).filter(
        File.filepath.contains(presentation+'.txt')
    ).first()
    pres_user = db_session.query(PresentationUser).filter(
        PresentationUser.presentation_id == a.presentation_id
    ).first()
    pres = db_session.query(Presentation).filter(
        Presentation.id == a.presentation_id
    ).first()
    if current_user.id == pres_user.user_id:
        if request.method == "POST":
            txt = request.form['text']
            # Make sure text is not null
            if len(txt) > 0:
                print("YES!")
                write_text_file(presentation, txt)
            # Redirect back to presentation
            return redirect("/editor/{}".format(presentation))
        else:
            videos = GetVideos(pres)
            print(a.filepath)
            text = GetText(a.filepath)
            return render_template("editor.html", name=current_user.email, current=pres, videos=videos, text=text.replace("\n","\\n").replace("\r","\\r"), fname=presentation)
    else:
        return redirect("/editor/new")


@editor_pages.route("/new", methods=["GET", "POST"])
@auth_required()
def new():
    if request.method == "POST":
        title = request.form['title']
        lang = request.form['languages']
        if 'translate' in request.form:
            translate = True
        else:
            translate = False
        if 'gen-image' in request.form:
            genimages = True
        else:
            genimages = False
        text = request.form['text']
        if len(text) <= 1:
            return render_template("new.html")
        else:
            fname = NewPresentation(title, lang, translate, genimages, text)
            return redirect("/editor/{}".format(fname))
    return render_template("new.html", name=current_user.email, presentations=current_user.presentations)


@editor_pages.route("/submitted")
@auth_required()
def submitted():
    return render_template("submitted.html")


def NewPresentation(title, language, translate, genimages, text):
    fname = str(uuid.uuid4())
    write_text_file(fname, text)
    time = datetime.datetime.now()
    p = Presentation(title=title, ctime=time, mtime=time,
                     translate=translate, genimages=genimages)
    f = File(language=language, ctime=time, mtime=time,
             filepath="{}.txt".format(fname))
    p.files.append(f)
    curr_usr = db_session.query(User).filter(
        User.id == current_user.id).first()
    curr_usr.presentations.append(p)
    db_session.add(p)
    db_session.add(f)
    db_session.add(curr_usr)
    db_session.commit()
    return fname


def write_text_file(fname, text):
    """ Writes text to file fname"""
    # Save text to file
    upload_file_from_txt(fname+'.txt', text)
#    print(fname, text)
#    with open('static/uploads/{}.txt'.format(fname), 'w') as f:
#        f.writelines(text)


def GetText(filepath):
    """Returns the text of file"""
    txt = ''
    return load_file_text(filepath)
#    with open(filepath, 'r') as f:
#        for line in f.readlines():
#            txt += line
#    return txt


def GetVideos(presentation):
    vids = []
    for f in presentation.files:
        if f.ftype == 'video':
            vids.append(f)
    return vids

@editor_pages.route("/video/<video_id>", methods=["GET"])
@auth_required()
def stream_video(video_id):
    return video_id
    current_user

server/views/pay.py
import os
import stripe
from flask import Blueprint, flash, render_template, request, url_for, current_app, abort, jsonify
from flask_security import current_user, auth_required
from werkzeug.utils import redirect

payment_pages = Blueprint("payment_pages", __name__, url_prefix='/pay')

stripe_keys = {
    "secret": os.environ["STRIPE_SECRET_KEY"],
    "public": os.environ["STRIPE_PUBLIC_KEY"],
    "endpoint": os.environ["STRIPE_ENDPOINT_SECRET"]
}

stripe.api_key = stripe_keys["secret"]


@payment_pages.route("/", methods=["GET"])
@auth_required()
def pay():
    return render_template("pay.html", user=current_user)


@payment_pages.route("/config")
def get_payment_config():
    stripe_config = {"publicKey": stripe_keys["public"]}
    return jsonify(stripe_config)


@payment_pages.route("/success")
def success():
    return render_template("success.html")


@payment_pages.route("/cancelled")
def cancel():
    return render_template("cancelled.html")


@payment_pages.route("/stripehook",  methods=["POST"])
def stripe_webhook():
    payload = request.get_data(as_text=True)
    sig_header = request.headers.get("Stripe-Signature")

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, stripe_keys["endpoint"]
        )

    except ValueError as e:
        return "Invalid payload", 400

    except stripe.error.SignatureVerificationError as e:
        return "Invalid signature", 400

    if event["type"] == "checkout.session.completed":
        print("Payment success")

    return "Success", 200


@payment_pages.route("/create-checkout-session/<credits>")
@auth_required()
def create_checkout_session(credits=0):
    domain_url = "http://127.0.0.1:5000/pay/"
    stripe.api_key = stripe_keys['secret']
    try:
        checkout_session = stripe.checkout.Session.create(
            client_reference_id=current_user.id,
            success_url=domain_url +
            "success?session_id={CHECKOUT_SESSION_ID}",
            cancel_url=domain_url + "cancelled",
            payment_method_types=["card"],
            mode="payment",
            line_items=[
                {
                    "name": "credits",
                    "quantity": credits,
                    "currency": "usd",
                    "amount": "100"  # str(int(credits) * 100)
                }
            ]
        )
        return jsonify({"sessionId": checkout_session["id"]})
    except Exception as e:
        return jsonify(error=str(e)), 403
    # return domain_url

server/views/test.py
import os
from flask import Blueprint, flash, render_template, request, url_for, current_app, abort
from flask_security import current_user, auth_required
from werkzeug.utils import redirect

profile_pages = Blueprint("profile_pages", __name__, url_prefix='/profile')

@profile_pages.route("/", methods=["GET"])
@auth_required()
def dump():
    return render_template("test.html", name=current_user.email, presentations=current_user.presentations)

server/templates/about.html
{% extends 'base.html' %}
{% block title %}About{% endblock title %}
{% block meta %}
    <!-- Tell robots we love them -->
    <meta name=”robots” content=”index, follow”>{% endblock meta %}
{% block body %}
        <h1>About</h1>
        <article>
            <p class="figure">
                Presently was created as part of Noah Wood's coursework
                at <a href="https://www.baker.edu">Baker College</a>.
                Presently uses the latest in artifical intelligence
                technologies such as DALL-E to quickly and easily create 
                narrated presentations from text files, markdown, and html!
            </p>
            {% include 'partials/call_to_action.html' %}
        </article>
    {% endblock body %}

server/templates/base.html
<!DOCTYPE html>
<html class="no-js" lang="en">

<!-- Header-->

<head>
    <!-- Title should be different for accessibility-->
    <title>Presently | {% block title %}{% endblock title %}</title>
    <!-- Meta tags -->{% block meta %}{% endblock meta %}
    {% include 'partials/header.html' %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/widescreen.css') }}">
<!--    <link rel="stylesheet" media="screen and (min-width: 1500px)" href="{{ url_for('static', filename='css/widescreen.css') }}">
    <link rel="stylesheet" media="screen and (max-width: 1499px)" href="{{ url_for('static', filename='css/smallscreen.css') }}">-->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
    {% block css %}{% endblock css %}
    <!-- Put any js that cannot run late here -->{% block earlyjs %}{% endblock earlyjs %}
</head>

<!-- Body -->

<body style="margin:1rem">
    <!--Navbar -->
    {% include 'partials/navbar.html' %}
    <!-- Wrapper -->
    <div class="wrapper">
        <!-- Main Content -->
        <main role="main" class="main-content">
            {% block body %}{% endblock body %}
        </main>
        {% block aside %}<aside></aside>{% endblock aside %}
    </div>
    <!-- Footer -->
    {% include 'partials/footer.html' %}
    <!-- Add javascript here -->{% block javascript %}{% endblock javascript %}
</body>

</html>

server/templates/cancelled.html
{% extends 'base.html' %}
{% block meta %}
    <!-- Tell robots we hate them -->
    <meta name=”robots” content=”index, nofollow”>{% endblock meta %}
{% block title %}Home{% endblock title %}
{% block body %}
        <h1>Cancel</h1>

        <p>Your payment was cancelled.</p>
    {% endblock body %}

server/templates/editor.html
{% extends 'base.html' %}
{% block title %}{{ current.title }}{% endblock %}
{% block body %}
<article>
    {% include 'partials/presentation_view.html' %}
    {% include 'partials/presentation_form.html' %}
</article>
{% endblock %}

server/templates/editor_base.html
<!DOCTYPE html>
<html class="no-js" lang="en">

<!-- Header-->

<head>
    <!-- Title should be different for accessibility-->
    <title>Presently | {% block title %}{% endblock title %}</title>
    <!-- Meta tags -->{% block meta %}{% endblock meta %}
    {% include 'partials/header.html' %}
<!--    <link rel="stylesheet" href="{{ url_for('static', filename='css/editor.css') }}">
-->    {% block css %}{% endblock css %}
    <!-- Put any js that cannot run late here -->
    {% block earlyjs %}{% endblock earlyjs %}
</head>

<!-- Body -->

<body style="margin:1rem">
    <!--Navbar -->
    {% include 'partials/navbar.html' %}
    <!-- Main Content -->
    <main class="main-content">{% block body %}{% endblock body %}</main>
    <!-- Footer -->
    {% include 'partials/footer.html' %}
    <!-- Add javascript here -->{% block javascript %}{% endblock javascript %}
</body>

</html>

server/templates/index.html
{% extends 'base.html' %}
{% block meta %}
    <!-- Tell robots we love them -->
    <meta name=”robots” content=”index, follow”>{% endblock meta %}
{% block title %}Home{% endblock title %}
{% block body %}
        <h1>Presently</h1>
        <article>
            <figure>
                <img src="{{ url_for('static', filename='imgs/Hotpot.png') }}" alt="Cave image generated by the Dall-E AI">
                <figcaption><button big>Watch It Work!</button></figcaption>
                <br />
                <p>Welcome to Presently!</p>
                <p>Our technology allows you to create beautiful and entertaining</p>
                <p>presentations from any text, markdown, or html file you have!</p>
            </figure>
            {% include 'partials/call_to_action.html' %}
        </article>

    {% endblock body %}

server/templates/new.html
{% extends 'base.html' %}
{% block title %}New{% endblock title %}

{% block body %}
<div>
    <h1>New Presentation</h1>
    <form method="POST" href="/editor/new">
        <fieldset style="float:left; text-align:left; width: 40%; border:0;">
            <h3>Settings</h3>
            <label for="title">Project Title:</label>
            <input type="text" id="title" name="title" />
            <br />
            <label for="languages">Voices</label>
            <select class="list-dt" id="languages" name="languages" onchange="UpdateAudioTest()">
                <option value="en-US-Neural2-A" selected="selected">English (US)</option>
                <option value="en-GB-Neural2-A">English (UK)</option>
                <option value="en-AU-Neural2-A">English (Australia)</option>
                <option value="es-US-Neural2-A">Spanish (US)</option>
            </select>
            <a class="label" for="testAudio" onclick="PlayTestAudio()">Test</a>
            <audio id="testAudio" preload="none">
                <source id="testSource" type="audio/wav">
                Your browser does not support the audio element.
            </audio>
            <br />
            <label for="translate">Auto-translate?</label>
            <input id="translate" name="translate" type="checkbox" checked><br />
            <label for="gen-image">Generate Images</label>
            <input id="gen-image" name="gen-image" type="checkbox" checked>

        </fieldset>
        <fieldset style="border:0;">
        <textarea id="text" name="text" cols="40" rows="10" spellcheck="true" style="border-radius:.5rem;"></textarea>
        </fieldset>
        <fieldset style="width:100%; border:0;">
        <button>Submit</button>
    </fieldset>
    </form>
</div>
{% endblock body %}

{% block javascript %}

<script>
    var wiz3Lang = document.getElementById("languages");
var wiz3Audio = document.getElementById("testAudio");
var wiz3AudioSrc = document.getElementById("testSource");
var wiz3US = "{{url_for('static', filename='audio/en-US-Neural2-A.wav') }}"
var wiz3UK = "{{url_for('static', filename='audio/en-GB-Neural2-A.wav') }}"
var wiz3AU = "{{url_for('static', filename='audio/en-AU-Neural2-A.wav') }}"
var wiz3Es = "{{url_for('static', filename='audio/es-US-Neural2-A.wav') }}"
var newAudioSrc = wiz3US;
function UpdateAudioTest()
{
    if (wiz3Lang.value.includes('es')) {
        newAudioSrc = wiz3Es;
    }   
    else if (wiz3Lang.value.includes('US')) {
        newAudioSrc = wiz3US;
    }
    else if (wiz3Lang.value.includes('GB')) {
        newAudioSrc = wiz3UK;
    }
    else if (wiz3Lang.value.includes('AU')) {
        newAudioSrc = wiz3AU;
    }
    wiz3AudioSrc.setAttribute("src", newAudioSrc);
    wiz3Audio.load();
}
UpdateAudioTest();

function PlayTestAudio()
{
    wiz3Audio.play();
}
</script>
{% endblock javascript %}

server/templates/pay.html
{% extends 'base.html' %}
{% block meta %}
    <!-- Tell robots we hate them -->
    <meta name=”robots” content=”index, nofollow”>{% endblock meta %}
{% block title %}Pay{% endblock title %}
{% block body %}
        <h1>Presently</h1>
            {% include 'partials/wallet.html' %}
            {% include 'partials/order_form.html' %}
        </div>
    {% endblock body %}

{% block javascript %}
<script src="https://js.stripe.com/v3/"></script>
<script>
    console.log("Sanity");
    fetch("/pay/config")
    .then((result) => { return result.json(); })
    .then((data) => {
        const stripe = Stripe(data.publicKey);
    
        // New event handler
        document.querySelector("#orderBtn").addEventListener("click", () => {
            var credits = document.getElementById("quantity").value;
            fetch("/pay/create-checkout-session/"+credits)
            .then((result) => { return result.json(); })
            .then((data) => {
                console.log(data);
                return stripe.redirectToCheckout({sessionId: data.sessionId})
            })
            .then((res) => {
                console.log(res);
            });
        });
    });
</script>

{% endblock %}

server/templates/pricing.html
{% extends 'base.html' %}
{% block title %}Pricing{% endblock title %}
{% block meta %}
    <!-- Tell robots we love them -->
    <meta name=”robots” content=”index, follow”>{% endblock meta %}
{% block body %}
        <h1 style="text-align: center;">Pricing</h1>
        <article>
            <div class="main-text">
                <h2>Credit Based Pricing</h2>
                <p>We currently use a credits pricing model, each credit costs $1 USD and provides you with the ability to generate up to 5 slides and narrate 1500 words.
                Simply load your <a href="{{ url_for('payment_pages.pay') }}">wallet</a> and start making presentations!</p>
                <p>To help you get started, we'll give you a free trial credit when you sign up!</p>
            </div>
            {% include 'partials/call_to_action.html' %}
        </article>
    {% endblock body %}

server/templates/privacy.html
{% extends 'base.html' %}
{% block title %}Privacy Policy{% endblock title %}
{% block meta %}
<!-- Tell robots we love them -->
<meta name=”robots” content=”index, follow”>{% endblock meta %}
{% block body %}
<h1>Presently TOS</h1>
<!-- This was generated using termsly, not my work!!!-->
    <iframe src="{{ url_for('privacy_termly') }}" class="embedded">
        
    </iframe>
{% endblock body %}

server/templates/submitted.html
{% extends 'base.html' %}
{% block title %}New{% endblock title %}

{% block body %}
<div>
    <h1>Submitted!</h1>
</div>
{% endblock body %}

server/templates/success.html
{% extends 'base.html' %}
{% block meta %}
    <!-- Tell robots we hate them -->
    <meta name=”robots” content=”index, nofollow”>{% endblock meta %}
{% block title %}Home{% endblock title %}
{% block body %}
        <h1>Success</h1>

        <p>Your payment succeeded!</p>
    {% endblock body %}

server/templates/test.html
{% extends 'base.html' %}
{% block title %}My Presentations{% endblock %}
{% block body %}
<h1>{{ name }}</h1>
<ul>
    {% for presentation in presentations %}
    <li>{{ presentation.title }} | {{ presentation.files[0].filepath }}</li>
    {% endfor %}
</ul>
{% endblock %}